# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Onkar Koli
tagline:          'Security Engineer'
description:      'Product Security Engineer at SolarWinds'
url:              https://onkark.com
baseurl:          ''  # Empty for custom domain

author:
  name:           'Onkar Koli'
  url:            https://github.com/0nk4r

paginate:         5
paginate_path:    '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/blog/'

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - .stylelintrc.json

# Google analytics
# google_analytics: 'UA-144594777-1'

# Disqus
disqus:
  shortname: hanbinpage
