# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Onkar Koli
tagline:          'Security Engineer'
description:      'Product Security Engineer at SolarWinds, specializing in application security, secure development practices, and security architecture.'
url:              https://onkark.com
baseurl:          ''  # Empty for custom domain

author:
  name:           'Onkar Koli'
  url:            https://github.com/0nk4r
  email:          contact@onkark.com

# SEO
keywords:         [security engineering, application security, threat modeling, secure development, cybersecurity]
lang:             en-US
locale:           en_US
timezone:         UTC

paginate:         5
paginate_path:    '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/blog/'

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - .stylelintrc.json

# Google analytics
# google_analytics: 'UA-144594777-1'

# Disqus
disqus:
  shortname: hanbinpage
